Internet engineering/simple_site_for_semantic-similarity-tool/config/routes.rb
Rails.application.routes.draw do
	get 'wordnet_disco_sems/new'
	resources :wordnet_disco_sems
	root 'wordnet_disco_sems#new'
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Internet engineering/simple_site_for_semantic-similarity-tool/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Internet engineering/simple_site_for_semantic-similarity-tool/app/models/wordnet_disco_sem.rb
class WordnetDiscoSem < ApplicationRecord
end

Internet engineering/simple_site_for_semantic-similarity-tool/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Internet engineering/simple_site_for_semantic-similarity-tool/app/controllers/wordnet_disco_sems_controller.rb
class WordnetDiscoSemsController < ApplicationController
  before_action :set_wordnet_disco_sem, only: [:show, :edit, :update, :destroy]

  # GET /wordnet_disco_sems
  # GET /wordnet_disco_sems.json
  def index
    @wordnet_disco_sems = WordnetDiscoSem.all
  end

  # GET /wordnet_disco_sems/1
  # GET /wordnet_disco_sems/1.json
  def show
  end

  # GET /wordnet_disco_sems/new
  def new
    @wordnet_disco_sem = WordnetDiscoSem.new
  end

  # GET /wordnet_disco_sems/1/edit
  def edit
  end

  # POST /wordnet_disco_sems
  # POST /wordnet_disco_sems.json
  def create
    @wordnet_disco_sem = WordnetDiscoSem.new(wordnet_disco_sem_params)

    respond_to do |format|
      if @wordnet_disco_sem.save
        format.html { redirect_to @wordnet_disco_sem, notice: 'Wordnet disco sem was successfully created.' }
        format.json { render :show, status: :created, location: @wordnet_disco_sem }
      else
        format.html { render :new }
        format.json { render json: @wordnet_disco_sem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wordnet_disco_sems/1
  # PATCH/PUT /wordnet_disco_sems/1.json
  def update
    respond_to do |format|
      if @wordnet_disco_sem.update(wordnet_disco_sem_params)
        format.html { redirect_to @wordnet_disco_sem, notice: 'Wordnet disco sem was successfully updated.' }
        format.json { render :show, status: :ok, location: @wordnet_disco_sem }
      else
        format.html { render :edit }
        format.json { render json: @wordnet_disco_sem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wordnet_disco_sems/1
  # DELETE /wordnet_disco_sems/1.json
  def destroy
    @wordnet_disco_sem.destroy
    respond_to do |format|
      format.html { redirect_to wordnet_disco_sems_url, notice: 'Wordnet disco sem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wordnet_disco_sem
      @wordnet_disco_sem = WordnetDiscoSem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wordnet_disco_sem_params
      params.require(:wordnet_disco_sem).permit(:textb1, :textb2, :disco_result, :wordnet_result, :tfidf)
    end
end

Internet engineering/simple_site_for_semantic-similarity-tool/app/helpers/application_helper.rb
module ApplicationHelper
end

Internet engineering/simple_site_for_semantic-similarity-tool/app/helpers/wordnet_disco_sems_helper.rb
module WordnetDiscoSemsHelper
end

Internet engineering/simple_site_for_semantic-similarity-tool/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SemanticSimilarityTool</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Internet engineering/simple_site_for_semantic-similarity-tool/app/views/wordnet_disco_sems/_form.html.erb
<%= form_for(wordnet_disco_sem) do |f| %>
  <% if wordnet_disco_sem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wordnet_disco_sem.errors.count, "error") %> prohibited this wordnet_disco_sem from being saved:</h2>

      <ul>
      <% wordnet_disco_sem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :textb1 %>
    <%= f.text_area :textb1 %>
  </div>

  <div class="field">
    <%= f.label :textb2 %>
    <%= f.text_area :textb2 %>
  </div>

  <!-- <div class="field">
    <%= f.label :disco_result %>
    <%= f.text_field :disco_result %>
  </div>

  <div class="field">
    <%= f.label :wordnet_result %>
    <%= f.text_field :wordnet_result %>
  </div>

  <div class="field">
    <%= f.label :tfidf %>
    <%= f.text_field :tfidf %>
  </div>
 -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<!-- <html>
    <head>
        
        <style>
            textarea { width: 100%; height: 75px }
        </style>
    </head>
    <body>
        <textarea class="comments"></textarea>
    </body>
</html> -->
<div>
  <table>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Points</th>
    </tr>
    <tr>
      <td>Peter</td>
      <td>Griffin</td>
      <td>$100</td>
    </tr>
    <tr>
      <td>Lois</td>
      <td>Griffin</td>
      <td>$150</td>
    </tr>
    <tr>
      <td>Joe</td>
      <td>Swanson</td>
      <td>$300</td>
    </tr>
    <tr>
      <td>Cleveland</td>
      <td>Brown</td>
      <td>$250</td>
    </tr>
  </table>
</div>

Internet engineering/simple_site_for_semantic-similarity-tool/app/views/wordnet_disco_sems/edit.html.erb
<h1>Editing Wordnet Disco Sem</h1>

<%= render 'form', wordnet_disco_sem: @wordnet_disco_sem %>

<%= link_to 'Show', @wordnet_disco_sem %> |
<%= link_to 'Back', wordnet_disco_sems_path %>

Internet engineering/simple_site_for_semantic-similarity-tool/app/views/wordnet_disco_sems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wordnet Disco Sems</h1>

<table>
  <thead>
    <tr>
      <th>Textb1</th>
      <th>Textb2</th>
      <th>Disco result</th>
      <th>Wordnet result</th>
      <th>Tfidf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wordnet_disco_sems.each do |wordnet_disco_sem| %>
      <tr>
        <td><%= wordnet_disco_sem.textb1 %></td>
        <td><%= wordnet_disco_sem.textb2 %></td>
        <td><%= wordnet_disco_sem.disco_result %></td>
        <td><%= wordnet_disco_sem.wordnet_result %></td>
        <td><%= wordnet_disco_sem.tfidf %></td>
        <td><%= link_to 'Show', wordnet_disco_sem %></td>
        <td><%= link_to 'Edit', edit_wordnet_disco_sem_path(wordnet_disco_sem) %></td>
        <td><%= link_to 'Destroy', wordnet_disco_sem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wordnet Disco Sem', new_wordnet_disco_sem_path %>

Internet engineering/simple_site_for_semantic-similarity-tool/app/views/wordnet_disco_sems/new.html.erb
<h1>New Wordnet Disco Sem</h1>

<%= render 'form', wordnet_disco_sem: @wordnet_disco_sem %>

<%= link_to 'Back', wordnet_disco_sems_path %>

Internet engineering/simple_site_for_semantic-similarity-tool/app/views/wordnet_disco_sems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Textb1:</strong>
  <%= @wordnet_disco_sem.textb1 %>
</p>

<p>
  <strong>Textb2:</strong>
  <%= @wordnet_disco_sem.textb2 %>
</p>

<p>
  <strong>Disco result:</strong>
  <%= @wordnet_disco_sem.disco_result %>
</p>

<p>
  <strong>Wordnet result:</strong>
  <%= @wordnet_disco_sem.wordnet_result %>
</p>

<p>
  <strong>Tfidf:</strong>
  <%= @wordnet_disco_sem.tfidf %>
</p>

<%= link_to 'Edit', edit_wordnet_disco_sem_path(@wordnet_disco_sem) %> |
<%= link_to 'Back', wordnet_disco_sems_path %>